CREATE TABLE `userPreferences` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`languageCode` varchar(32) DEFAULT 'en',
	`beliefSystem` varchar(64),
	`voicePersona` varchar(32) DEFAULT 'neutral',
	`voicePitch` varchar(10) DEFAULT '1.0',
	`voiceRate` varchar(10) DEFAULT '1.0',
	`autoPlayTTS` boolean DEFAULT false,
	`preferredGroundingCategory` varchar(64),
	`culturalContext` varchar(64),
	`communityContext` varchar(64),
	`themePreference` enum('dark','light','system') DEFAULT 'dark',
	`fontSize` enum('small','medium','large','xlarge') DEFAULT 'medium',
	`reduceMotion` boolean DEFAULT false,
	`highContrast` boolean DEFAULT false,
	`subscriptionTier` enum('free','premium','professional') DEFAULT 'free',
	`stripeCustomerId` varchar(255),
	`stripeSubscriptionId` varchar(255),
	`subscriptionStatus` varchar(32) DEFAULT 'inactive',
	`subscriptionEndDate` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `userPreferences_id` PRIMARY KEY(`id`),
	CONSTRAINT `userPreferences_userId_unique` UNIQUE(`userId`)
);
