import { Link } from "wouter";
import { ArrowLeft, AlertTriangle, Phone, Heart, Shield, Brain } from "lucide-react";

export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="container max-w-4xl py-12">
        <Link href="/" className="inline-flex items-center gap-2 text-emerald-400 hover:text-emerald-300 mb-8">
          <ArrowLeft className="w-4 h-4" />
          Back to Home
        </Link>

        <h1 className="text-4xl font-bold mb-2">Disclaimer</h1>
        <p className="text-muted-foreground mb-8">Last Updated: January 25, 2026</p>

        <div className="prose prose-invert max-w-none space-y-8">
          
          {/* Required Global Disclaimer - exact text per compliance directive */}
          <div className="bg-blue-500/15 border-2 border-blue-500/50 rounded-lg p-6">
            <p className="text-lg text-white/90 font-medium leading-relaxed mb-0">
              ReUnity is a wellness and support tool. It is not a medical device and does not provide diagnosis, treatment, or crisis services. If you are in immediate danger, call 911 or your local emergency services.
            </p>
          </div>

          {/* Emergency Banner */}
          <div className="bg-red-500/20 border-2 border-red-500 rounded-lg p-6">
            <div className="flex items-start gap-4">
              <AlertTriangle className="w-8 h-8 text-red-500 flex-shrink-0 mt-1" />
              <div>
                <h2 className="text-xl font-bold text-red-400 mt-0 mb-2">If You Are in Crisis</h2>
                <p className="mb-4">If you are experiencing a mental health emergency, having thoughts of suicide, or are in immediate danger:</p>
                <div className="grid gap-3">
                  <a href="tel:988" className="flex items-center gap-3 bg-red-500/20 rounded-lg p-3 hover:bg-red-500/30 transition-colors">
                    <Phone className="w-5 h-5 text-red-400" />
                    <span><strong>Call 988</strong> - Suicide & Crisis Lifeline (24/7)</span>
                  </a>
                  <a href="tel:911" className="flex items-center gap-3 bg-red-500/20 rounded-lg p-3 hover:bg-red-500/30 transition-colors">
                    <Phone className="w-5 h-5 text-red-400" />
                    <span><strong>Call 911</strong> - Emergency Services</span>
                  </a>
                  <a href="sms:741741&body=HELLO" className="flex items-center gap-3 bg-red-500/20 rounded-lg p-3 hover:bg-red-500/30 transition-colors">
                    <Phone className="w-5 h-5 text-red-400" />
                    <span><strong>Text HOME to 741741</strong> - Crisis Text Line</span>
                  </a>
                </div>
              </div>
            </div>
          </div>

          {/* Main Disclaimer */}
          <section>
            <h2 className="text-2xl font-semibold text-white flex items-center gap-3">
              <Brain className="w-6 h-6 text-emerald-400" />
              Mental Health Disclaimer
            </h2>
            <div className="bg-amber-500/10 border border-amber-500/30 rounded-lg p-6">
              <p className="font-semibold text-amber-400 mb-4">PLEASE READ CAREFULLY:</p>
              <ul className="space-y-3">
                <li><strong>ReUnity is NOT a substitute for professional mental health treatment.</strong> It is a supportive tool designed to complement—not replace—therapy, counseling, or psychiatric care.</li>
                <li><strong>The AI companion is NOT a licensed mental health professional.</strong> It cannot diagnose conditions, prescribe medications, or provide clinical treatment.</li>
                <li><strong>Responses are generated by artificial intelligence</strong> and may not always be accurate, appropriate, or applicable to your specific situation.</li>
                <li><strong>Do NOT rely solely on ReUnity</strong> for managing serious mental health conditions including but not limited to: depression, anxiety disorders, PTSD, bipolar disorder, schizophrenia, eating disorders, or substance use disorders.</li>
                <li><strong>Always consult qualified healthcare providers</strong> for diagnosis, treatment, and medical advice.</li>
              </ul>
            </div>
          </section>

          {/* Data & Confidentiality */}
          <section>
            <h2 className="text-2xl font-semibold text-white flex items-center gap-3">
              <Shield className="w-6 h-6 text-emerald-400" />
              Data & Confidentiality Notice
            </h2>
            <div className="bg-emerald-500/10 border border-emerald-500/30 rounded-lg p-6">
              <p className="font-semibold text-emerald-400 mb-4">YOUR PRIVACY MATTERS:</p>
              <ul className="space-y-3">
                <li><strong>Conversation data is NOT permanently stored.</strong> Your chat sessions are processed in real-time and are not retained on our servers after the session ends.</li>
                <li><strong>We do NOT sell, share, or monetize your personal information.</strong></li>
                <li><strong>Journal entries and safety plans are stored locally</strong> on your device and encrypted. You control your data.</li>
                <li><strong>We cannot access your conversations.</strong> No human reviews your chats with the AI.</li>
                <li><strong>Anonymous usage analytics</strong> may be collected to improve the service, but this data cannot identify you personally.</li>
              </ul>
            </div>
          </section>

          {/* Limitation of Liability */}
          <section>
            <h2 className="text-2xl font-semibold text-white">Limitation of Liability</h2>
            <div className="bg-gray-800/50 rounded-lg p-6">
              <p>TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW:</p>
              <ul className="space-y-3 mt-4">
                <li>REOP Solutions, its developers, affiliates, and partners <strong>SHALL NOT BE LIABLE</strong> for any damages, injuries, or losses arising from your use of ReUnity.</li>
                <li>We are <strong>NOT RESPONSIBLE</strong> for any decisions you make based on information or support provided by the App.</li>
                <li>We <strong>MAKE NO GUARANTEES</strong> about the effectiveness, accuracy, or appropriateness of the AI's responses for your individual circumstances.</li>
                <li>Use of ReUnity is <strong>AT YOUR OWN RISK</strong>.</li>
              </ul>
            </div>
          </section>

          {/* AI Limitations */}
          <section>
            <h2 className="text-2xl font-semibold text-white">AI Limitations</h2>
            <p>ReUnity uses artificial intelligence to provide support. Please understand:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>The AI may occasionally provide responses that are incorrect, incomplete, or not applicable to your situation</li>
              <li>The AI cannot understand context the way a human therapist can</li>
              <li>The AI may not recognize all crisis situations or respond appropriately in every case</li>
              <li>The AI's knowledge has limitations and may not reflect the most current research or best practices</li>
              <li>The AI cannot form a therapeutic relationship or provide the nuanced care of a human professional</li>
            </ul>
          </section>

          {/* Peer Support Disclaimer */}
          <section>
            <h2 className="text-2xl font-semibold text-white flex items-center gap-3">
              <Heart className="w-6 h-6 text-emerald-400" />
              Peer Support Disclaimer
            </h2>
            <p>If you use ReUnity's peer support features:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Other users are <strong>NOT mental health professionals</strong> unless explicitly stated</li>
              <li>Advice from peers should <strong>NOT replace professional guidance</strong></li>
              <li>We <strong>cannot guarantee the accuracy</strong> of information shared by other users</li>
              <li>We are <strong>NOT responsible for the actions</strong> of other users</li>
              <li>Report any concerning behavior immediately using the in-app reporting feature</li>
            </ul>
          </section>

          {/* Age Restriction */}
          <section>
            <h2 className="text-2xl font-semibold text-white">Age Restriction</h2>
            <p>ReUnity is intended for users <strong>17 years of age and older</strong>. By using this application, you confirm that you meet this age requirement. If you are under 17, please seek support from a trusted adult, school counselor, or contact:</p>
            <div className="bg-gray-800/50 rounded-lg p-4 mt-4">
              <p><strong>Childhelp National Child Abuse Hotline:</strong> 1-800-422-4453</p>
              <p><strong>Boys Town National Hotline:</strong> 1-800-448-3000</p>
            </div>
          </section>

          {/* No Guarantee */}
          <section>
            <h2 className="text-2xl font-semibold text-white">No Guarantee of Results</h2>
            <p>ReUnity is designed to provide support and resources, but:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>We <strong>cannot guarantee</strong> any specific outcomes or improvements in your mental health</li>
              <li>Individual results vary significantly based on many factors</li>
              <li>The effectiveness of grounding techniques and coping strategies differs for each person</li>
              <li>What works for one person may not work for another</li>
            </ul>
          </section>

          {/* Medical Emergency */}
          <section>
            <h2 className="text-2xl font-semibold text-white">Medical Emergency Protocol</h2>
            <div className="bg-red-500/10 border border-red-500/30 rounded-lg p-6">
              <p className="font-semibold mb-4">ReUnity is NOT equipped to handle medical emergencies. If you experience:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Thoughts of harming yourself or others</li>
                <li>A plan to end your life</li>
                <li>Severe panic attacks or psychotic episodes</li>
                <li>Symptoms of overdose or medical crisis</li>
                <li>Domestic violence or abuse situations requiring immediate safety</li>
              </ul>
              <p className="mt-4 font-semibold text-red-400">STOP USING THE APP AND CONTACT EMERGENCY SERVICES IMMEDIATELY.</p>
            </div>
          </section>

          {/* Acknowledgment */}
          <section>
            <h2 className="text-2xl font-semibold text-white">Your Acknowledgment</h2>
            <div className="bg-gray-800 border border-gray-700 rounded-lg p-6">
              <p>By using ReUnity, you acknowledge and agree that:</p>
              <ul className="list-disc pl-6 space-y-2 mt-4">
                <li>You have read and understood this Disclaimer</li>
                <li>You understand ReUnity is not a substitute for professional care</li>
                <li>You will seek professional help for serious mental health concerns</li>
                <li>You will contact emergency services if you are in crisis</li>
                <li>You accept the limitations of AI-powered support</li>
                <li>You use the Service at your own risk</li>
              </ul>
            </div>
          </section>

          {/* Contact */}
          <section>
            <h2 className="text-2xl font-semibold text-white">Questions?</h2>
            <p>If you have questions about this Disclaimer, please contact:</p>
            <div className="bg-gray-800/50 rounded-lg p-4 mt-4">
              <p><strong>Email:</strong> <a href="mailto:support@reunity.app" className="text-emerald-400">support@reunity.app</a></p>
              <p><strong>Developer:</strong> Christopher Ezernack</p>
              <p><strong>REOP Solutions</strong></p>
            </div>
          </section>

        </div>

        <div className="mt-12 pt-8 border-t border-gray-800 text-center text-sm text-muted-foreground">
          <p>© 2026 REOP Solutions. All rights reserved.</p>
          <div className="flex justify-center gap-4 mt-4">
            <Link href="/privacy" className="text-emerald-400 hover:underline">Privacy Policy</Link>
            <Link href="/terms" className="text-emerald-400 hover:underline">Terms of Service</Link>
          </div>
        </div>
      </div>
    </div>
  );
}
