import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Switch, Alert, Share } from 'react-native';
import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';

interface ReportOptions {
  moodData: boolean;
  sleepData: boolean;
  crisisEvents: boolean;
  medications: boolean;
  journalEntries: boolean;
  entropyScores: boolean;
}

export default function WellnessReportExport() {
  const [dateRange, setDateRange] = useState<'7' | '30' | '90'>('30');
  const [includeOptions, setIncludeOptions] = useState<ReportOptions>({
    moodData: true,
    sleepData: true,
    crisisEvents: true,
    medications: true,
    journalEntries: false,
    entropyScores: true,
  });
  const [isGenerating, setIsGenerating] = useState(false);

  const generateReport = async () => {
    setIsGenerating(true);
    try {
      // Generate report content
      const reportContent = generateReportContent();
      
      // Save to file
      const fileName = `wellness-report-${new Date().toISOString().split('T')[0]}.txt`;
      const filePath = `${FileSystem.documentDirectory}${fileName}`;
      await FileSystem.writeAsStringAsync(filePath, reportContent);
      
      // Share the file
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(filePath);
      } else {
        Alert.alert('Success', 'Report generated successfully');
      }
    } catch (error) {
      Alert.alert('Error', 'Failed to generate report');
    } finally {
      setIsGenerating(false);
    }
  };

  const generateReportContent = () => {
    const today = new Date();
    const startDate = new Date(today.getTime() - parseInt(dateRange) * 24 * 60 * 60 * 1000);
    
    let content = `WELLNESS REPORT\n`;
    content += `Generated: ${today.toLocaleDateString()}\n`;
    content += `Period: ${startDate.toLocaleDateString()} - ${today.toLocaleDateString()}\n`;
    content += `\n${'='.repeat(50)}\n\n`;

    if (includeOptions.moodData) {
      content += `MOOD TRACKING\n`;
      content += `-`.repeat(30) + `\n`;
      content += `Average Mood: 6.5/10\n`;
      content += `Mood Range: 4 - 8\n`;
      content += `Most Common: Calm, Hopeful\n`;
      content += `Days Logged: ${Math.floor(parseInt(dateRange) * 0.8)}\n\n`;
    }

    if (includeOptions.sleepData) {
      content += `SLEEP QUALITY\n`;
      content += `-`.repeat(30) + `\n`;
      content += `Average Duration: 7.2 hours\n`;
      content += `Average Quality: 72%\n`;
      content += `Sleep Consistency: Good\n\n`;
    }

    if (includeOptions.crisisEvents) {
      content += `CRISIS EVENTS\n`;
      content += `-`.repeat(30) + `\n`;
      content += `Total Events: 2\n`;
      content += `Severity: 1 High, 1 Moderate\n`;
      content += `Common Triggers: Work stress, Sleep deprivation\n\n`;
    }

    if (includeOptions.medications) {
      content += `MEDICATION ADHERENCE\n`;
      content += `-`.repeat(30) + `\n`;
      content += `Overall Adherence: 94%\n`;
      content += `Missed Doses: 3\n\n`;
    }

    if (includeOptions.entropyScores) {
      content += `ENTROPY ANALYSIS\n`;
      content += `-`.repeat(30) + `\n`;
      content += `Current Score: 42/100\n`;
      content += `Trend: Improving\n`;
      content += `Stability Index: 78%\n\n`;
    }

    content += `\n${'='.repeat(50)}\n`;
    content += `Generated by ReUnity Wellness App\n`;
    content += `https://entropy-physics-ai.com\n`;

    return content;
  };

  const shareViaEmail = async () => {
    try {
      const reportContent = generateReportContent();
      await Share.share({
        message: reportContent,
        title: 'Wellness Report',
      });
    } catch (error) {
      Alert.alert('Error', 'Failed to share report');
    }
  };

  const toggleOption = (key: keyof ReportOptions) => {
    setIncludeOptions(prev => ({ ...prev, [key]: !prev[key] }));
  };

  return (
    <ScrollView style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.title}>Wellness Report</Text>
        <Text style={styles.subtitle}>Generate reports for healthcare providers</Text>
      </View>

      {/* Date Range Selection */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Report Period</Text>
        <View style={styles.dateRangeButtons}>
          {[
            { value: '7', label: '7 Days' },
            { value: '30', label: '30 Days' },
            { value: '90', label: '90 Days' },
          ].map(option => (
            <TouchableOpacity
              key={option.value}
              style={[
                styles.dateButton,
                dateRange === option.value && styles.dateButtonActive,
              ]}
              onPress={() => setDateRange(option.value as '7' | '30' | '90')}
            >
              <Text
                style={[
                  styles.dateButtonText,
                  dateRange === option.value && styles.dateButtonTextActive,
                ]}
              >
                {option.label}
              </Text>
            </TouchableOpacity>
          ))}
        </View>
      </View>

      {/* Include Options */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Include in Report</Text>
        {[
          { key: 'moodData', label: 'Mood Tracking Data', icon: '😊' },
          { key: 'sleepData', label: 'Sleep Quality Data', icon: '🌙' },
          { key: 'crisisEvents', label: 'Crisis Events', icon: '⚠️' },
          { key: 'medications', label: 'Medication Adherence', icon: '💊' },
          { key: 'journalEntries', label: 'Journal Entries', icon: '📝' },
          { key: 'entropyScores', label: 'Entropy Scores', icon: '📊' },
        ].map(option => (
          <View key={option.key} style={styles.optionRow}>
            <Text style={styles.optionIcon}>{option.icon}</Text>
            <Text style={styles.optionLabel}>{option.label}</Text>
            <Switch
              value={includeOptions[option.key as keyof ReportOptions]}
              onValueChange={() => toggleOption(option.key as keyof ReportOptions)}
              trackColor={{ false: '#3f3f46', true: '#7c3aed' }}
              thumbColor={includeOptions[option.key as keyof ReportOptions] ? '#a78bfa' : '#71717a'}
            />
          </View>
        ))}
      </View>

      {/* Privacy Notice */}
      <View style={styles.privacyCard}>
        <Text style={styles.privacyIcon}>🔒</Text>
        <Text style={styles.privacyText}>
          Your data is encrypted and only shared when you explicitly export it.
          Reports are generated locally on your device.
        </Text>
      </View>

      {/* Export Buttons */}
      <View style={styles.exportButtons}>
        <TouchableOpacity
          style={[styles.exportButton, styles.downloadButton]}
          onPress={generateReport}
          disabled={isGenerating}
        >
          <Text style={styles.exportButtonText}>
            {isGenerating ? 'Generating...' : '📥 Download Report'}
          </Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={[styles.exportButton, styles.emailButton]}
          onPress={shareViaEmail}
        >
          <Text style={styles.exportButtonText}>📧 Share via Email</Text>
        </TouchableOpacity>
      </View>

      {/* Footer Link */}
      <View style={styles.footer}>
        <Text style={styles.footerText}>Powered by ReUnity</Text>
        <Text style={styles.footerLink}>entropy-physics-ai.com</Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0a0a0a', padding: 16 },
  header: { marginBottom: 24 },
  title: { fontSize: 24, fontWeight: 'bold', color: '#fff' },
  subtitle: { color: '#71717a', marginTop: 4 },
  section: { marginBottom: 24 },
  sectionTitle: { color: '#a1a1aa', fontSize: 14, fontWeight: '600', marginBottom: 12, textTransform: 'uppercase' },
  dateRangeButtons: { flexDirection: 'row', gap: 12 },
  dateButton: { flex: 1, padding: 12, borderRadius: 8, borderWidth: 1, borderColor: '#3f3f46', alignItems: 'center' },
  dateButtonActive: { backgroundColor: '#7c3aed', borderColor: '#7c3aed' },
  dateButtonText: { color: '#a1a1aa', fontWeight: '500' },
  dateButtonTextActive: { color: '#fff' },
  optionRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#27272a' },
  optionIcon: { fontSize: 20, marginRight: 12 },
  optionLabel: { flex: 1, color: '#fff', fontSize: 16 },
  privacyCard: { flexDirection: 'row', backgroundColor: '#1e3a5f', borderRadius: 12, padding: 16, marginBottom: 24, alignItems: 'center' },
  privacyIcon: { fontSize: 24, marginRight: 12 },
  privacyText: { flex: 1, color: '#93c5fd', fontSize: 14, lineHeight: 20 },
  exportButtons: { gap: 12, marginBottom: 24 },
  exportButton: { padding: 16, borderRadius: 12, alignItems: 'center' },
  downloadButton: { backgroundColor: '#7c3aed' },
  emailButton: { backgroundColor: '#065f46' },
  exportButtonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  footer: { alignItems: 'center', paddingVertical: 24 },
  footerText: { color: '#52525b', fontSize: 12 },
  footerLink: { color: '#10b981', fontSize: 12, marginTop: 4 },
});
